### ISSUE TITLE
NPC Shop become a real NPC.

### ISSUE THREAD

**Issue by Aztorius** [moomaxie/BetterShops#8]
Sometimes, after a long time the Villager Shops can move like a normal Villager.

When I try to change the Villager to a Chest Shop there is an error message, the Chest Shop appear normally, but the Villager still exist and I can kill him.

Error log :

```
[10:17:34] [Craft Scheduler Thread - 49/WARN]: Exception in thread "Craft Scheduler Thread - 49" 
[10:17:34] [Craft Scheduler Thread - 49/WARN]: org.apache.commons.lang.UnhandledException: Plugin BetterShops v2.0.9 generated an exception while executing task 705
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
    at max.hubbard.bettershops.Configurations.Permissions.hasPlayerBlacklistPerm(Permissions.java:85)
    at max.hubbard.bettershops.Menus.ShopMenus.ShopSettings.draw(ShopSettings.java:309)
    at max.hubbard.bettershops.Shops.Types.NPC.DeleteNPC.deleteNPC(DeleteNPC.java:50)
    at max.hubbard.bettershops.Menus.ShopMenus.ShopSettings$7.onAction(ShopSettings.java:223)
    at max.hubbard.bettershops.Listeners.ClickableActionListener$1.run(ClickableActionListener.java:51)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

Log when the plugin is loading : 

```
[09:41:42] [Server thread/INFO]: [BetterShops] Enabling BetterShops v2.0.9
[09:41:42] [Server thread/INFO]: BetterShops - Enabling BetterShops 2.0.9
[09:41:42] [Server thread/INFO]: BetterShops - Loading support for CraftBukkitv1.8.R3
[09:41:42] [Server thread/INFO]: BetterShops - Loading support for Holographic Displays
[09:41:42] [Server thread/INFO]:BetterShops - Using Metrics - http://mcstats.org
[09:41:42] [Server thread/INFO]: BetterShops - Starting Loading of Chest Shops (18) Via File
[09:41:42] [Server thread/INFO]: BetterShops - 50%
[09:41:42] [Server thread/INFO]: BetterShops - Done!
[09:41:42] [Server thread/INFO]: BetterShops - Loaded 18 Chest Shops
[09:41:42] [Server thread/INFO]: BetterShops - Some shops may still be initializing, this may last a few minutes
[09:41:42] [Server thread/INFO]: BetterShops - Loading Sign Shops...
[09:41:42] [Server thread/INFO]: BetterShops - Loaded 0 Sign Shops
[09:41:42] [Server thread/INFO]: BetterShops - NPC Shops will be loaded when needed.
[09:41:42] [Server thread/INFO]: BetterShops - Holographic Shops will be loaded when needed.
[09:41:42] [Server thread/INFO]: BetterShops - Done
```

**Comment by moomaxie** [comment]
Should be fixed in the next release.

**Comment by Aztorius** [comment]
I realized that it concerns all the NPC.
